### ISSUE TITLE
Right Click

### ISSUE THREAD

**Issue by Kierze** [kaos00723/RotMG_Client_27.7.X2#2]
MouseEvent.Right_Click is errored but i have 
-swfversion=15

inside compiler options. Any idea's?

**Comment by kaos00723** [comment]
Use Flex SDK 4.9.1 instead of 4.6.0, that will solve your issue.

**Comment by Kierze** [comment]
@kaos00723 Can you hmu with a link, i can only find 3.6

**Comment by kaos00723** [comment]
Here you go: [Flex SDK 4.9.1](https://www.dropbox.com/s/8g4uiku6xw16mcl/flex_sdk_4.9.1.rar?dl=0)

**Comment by Kierze** [comment]
@kaos00723 thanks man couldn't find this anywhere

**Comment by Kierze** [comment]
Yeah this is now fixed.

**Comment by kaos00723** [comment]
Good to hear!

**Comment by Bog624s** [comment]
This helped me alot too couldnt find that flex anywhere also...

**Comment by InfernapeRotMG** [comment]
Thanks for putting the 4.9.1 here.
