### ISSUE TITLE
What did you use to decompile the client?

### ISSUE THREAD

**Issue by slick1015** [kaos00723/RotMG_Client_27.7.X2#3]
The title says all.

**Comment by kaos00723** [comment]
It's stated in the Readme. Action Script Viewer (ASV) which is a commercial program from Buraks.

**Comment by slick1015** [comment]
@kaos00723 would you mind adding me on discord @ MrSlick#8691
I'm hoping to write a program to automatically make an Intellij project out of a RotMG swf and I want your opinion on some things.
